version: "3.8"
services:
  app:
    image: node:20.17.0
    container_name: "rocketseat-nodejs-desafio-02-daily-diet-api"
    ports:
      - "3334:3333"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm i && npm run dev"
